import {
  boschHoldouts,
  datasetEvidence,
  evidencePrinciple,
  evidenceTerms,
  evidenceTotals,
} from "../../lib/public-evidence";
import {
  kernelPlainTerms,
  publicKernelBoundary,
  publicKernels,
} from "../../lib/public-kernels";
import { siteUrl } from "../../lib/site";
import { ArrowIcon, SiteFooter, SiteHeader } from "../site-chrome";
import EvidenceLab from "./evidence-lab";
import styles from "./evidence.module.css";

export const metadata = {
  title: "Evidence Guide",
  description:
    "A newcomer-friendly guide to SAGE Suite’s public simulation, open-data evaluation, historical research record, terminology, rights boundaries, and limitations.",
  alternates: {
    canonical: "/evidence/",
  },
  openGraph: {
    title: "Evidence Guide | SAGE Suite",
    description:
      "See what SAGE tested, what each dataset contributed, what the statistics mean, and what the results do not prove.",
    url: "/evidence/",
    type: "article",
  },
  twitter: {
    title: "Evidence Guide | SAGE Suite",
    description:
      "A plain-language guide to SAGE’s simulation, open-data evaluation, historical research, and limitations.",
  },
};

const evidenceStructuredData = {
  "@context": "https://schema.org",
  "@type": "CollectionPage",
  name: "SAGE Suite public evidence guide",
  description:
    "A plain-language guide to the public simulation, Bosch open-data evaluation, historical dataset research, terminology, rights status, and limitations.",
  url: `${siteUrl}evidence/`,
  isPartOf: {
    "@type": "WebSite",
    name: "SAGE Suite",
    url: siteUrl,
  },
  about: datasetEvidence.map((dataset) => ({
    "@type": "Dataset",
    name: dataset.fullName,
    url: dataset.sourceUrl,
  })),
};

const evidenceStructuredDataJson = JSON.stringify(evidenceStructuredData).replace(
  /</g,
  "\\u003c",
);

const quickSteps = [
  {
    number: "01",
    title: "Organize the plan",
    body:
      "SAGE represents the manufacturing recipe—setups, tools, operations, and checks—in a form people can review.",
  },
  {
    number: "02",
    title: "Attach the evidence",
    body:
      "A recommendation keeps its sources, labels, missing values, and limitations instead of appearing as unsupported certainty.",
  },
  {
    number: "03",
    title: "Check, then ask a person",
    body:
      "An independent check comes before a qualified human decision. The software cannot approve itself or command a machine.",
  },
];

const evidenceClasses = [
  {
    label: "SIMULATED",
    title: "Public teaching replay",
    body:
      "Generated by a public script. Useful for inspecting data flow, labels, unknowns, and a fail-closed demo rule—not for claiming physical performance.",
  },
  {
    label: "OPEN-DATA EVALUATION",
    title: "Bosch vibration boundary",
    body:
      "A reproduced calculation over 1,702 real CNC recordings. It tests cross-machine vibration similarity, not anomaly accuracy.",
  },
  {
    label: "HISTORICAL · RIGHTS REVIEW",
    title: "Earlier research record",
    body:
      "NASA, NUAA, and PHM results remain useful scientific context, but their public reuse rights and current reproduction artifacts are not all established.",
  },
];

const glossaryTerms = [...kernelPlainTerms, ...evidenceTerms];

export default function EvidencePage() {
  return (
    <main className={styles.page}>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: evidenceStructuredDataJson }}
      />
      <SiteHeader />

      <section className={styles.hero} id="top">
        <div className={styles.heroCopy}>
          <div className="section-kicker">New to SAGE? Start here.</div>
          <h1>
            See what was tested.
            <span>Understand what it means.</span>
          </h1>
          <p>
            SAGE helps manufacturing teams review CNC process plans, keep
            recommendations tied to evidence, and leave the final decision with
            qualified people. This guide separates what is simulated, what used
            open physical-machine data, and what remains historical research.
          </p>
          <div className={styles.heroActions}>
            <a className="button button-primary" href="#guided-replay">
              Watch the guided replay
              <ArrowIcon />
            </a>
            <a className="button button-secondary" href="#kernels">
              Understand the five checks
            </a>
          </div>
          <div className={styles.heroBoundary}>
            <span>Advisory only</span>
            <span>No machine control</span>
            <span>Limits stay visible</span>
          </div>
        </div>
        <aside className={styles.heroGuide} aria-label="Choose your depth">
          <span>Choose your depth</span>
          <a href="#quick-tour">
            <strong>60 seconds</strong>
            <small>What the platform does</small>
          </a>
          <a href="#guided-replay">
            <strong>3 minutes</strong>
            <small>Interactive public replay</small>
          </a>
          <a href="#dataset-ledger">
            <strong>8 minutes</strong>
            <small>Results, limits, and sources</small>
          </a>
          <a href="#glossary">
            <strong>Reference</strong>
            <small>Every technical term explained</small>
          </a>
        </aside>
      </section>

      <section className={styles.quickTour} id="quick-tour">
        <div className={styles.sectionIntro}>
          <div>
            <div className="section-kicker">SAGE in 60 seconds</div>
            <h2>It is a review layer, not an autopilot.</h2>
          </div>
          <p>
            A CNC process plan is the manufacturing recipe for making a part.
            SAGE is being built to make that recipe and its supporting evidence
            easier to inspect as one accountable thread.
          </p>
        </div>
        <div className={styles.quickGrid}>
          {quickSteps.map((step) => (
            <article key={step.number}>
              <span>{step.number}</span>
              <h3>{step.title}</h3>
              <p>{step.body}</p>
            </article>
          ))}
        </div>
        <p className={styles.oneLineBoundary}>
          In plain English: SAGE can help a person understand a plan; it cannot
          run the machine.
        </p>
      </section>

      <section className={styles.kernelSection} id="kernels">
        <div className={styles.sectionIntro}>
          <div>
            <div className="section-kicker">Five assurance kernels</div>
            <h2>Five focused checks. Five reasons to refuse.</h2>
          </div>
          <p>
            “Kernel” here means a small, focused software check—not an operating
            system, machine controller, or certified safety device. Each kernel
            asks a different question before an advisory result can continue.
          </p>
        </div>
        <div className={styles.kernelGrid}>
          {publicKernels.map((kernel) => (
            <article key={kernel.number}>
              <header>
                <span>{kernel.number}</span>
                <h3>{kernel.shortName}</h3>
              </header>
              <p className={styles.kernelQuestion}>{kernel.question}</p>
              <div>
                <span>If the answer is no</span>
                <p>{kernel.action}</p>
              </div>
              <small>{kernel.value}</small>
            </article>
          ))}
        </div>
        <div className={styles.kernelBoundary}>
          <strong>Public description boundary</strong>
          <p>{publicKernelBoundary}</p>
        </div>
      </section>

      <section className={styles.classSection} aria-labelledby="classes-heading">
        <div className={styles.sectionIntro}>
          <div>
            <div className="section-kicker">Three evidence classes</div>
            <h2 id="classes-heading">Different evidence answers different questions.</h2>
          </div>
          <p>
            Keeping these classes separate prevents a polished simulation from
            being mistaken for real-machine validation.
          </p>
        </div>
        <div className={styles.classGrid}>
          {evidenceClasses.map((item) => (
            <article key={item.label}>
              <span>{item.label}</span>
              <h3>{item.title}</h3>
              <p>{item.body}</p>
            </article>
          ))}
        </div>
      </section>

      <section className={styles.labSection} id="guided-replay">
        <div className={styles.sectionIntro}>
          <div>
            <div className="section-kicker">Public simulation · 120 rows</div>
            <h2>A browser twin you can inspect, not just watch.</h2>
          </div>
          <p>
            This generic scene is synchronized to the same downloadable
            simulation data shown in the chart and readouts. It is a teaching
            interface, not a physical digital twin.
          </p>
        </div>
        <EvidenceLab />
        <div className={styles.labActions}>
          <a className="button button-primary" href="/simulation/">
            Inspect all 120 rows
            <ArrowIcon />
          </a>
          <a
            className="button button-secondary"
            href="/data/sage-public-simulation-v1.csv"
            download
          >
            Download the CSV
          </a>
        </div>
      </section>

      <section className={styles.lineageSection} id="dataset-ledger">
        <div className={styles.sectionIntro}>
          <div>
            <div className="section-kicker">Optional technical depth</div>
            <h2>The supporting research ledger.</h2>
          </div>
          <p>
            Dataset work is one supporting part of the suite, not its organizing
            idea. Open this ledger to trace which sources informed separate
            experiments and where the evidence or reuse rights remain limited.
          </p>
        </div>

        <details className={styles.datasetDisclosure}>
          <summary>
            <span>
              Open the five-source research ledger
              <small>{evidencePrinciple}</small>
            </span>
            <strong>{evidenceTotals.datasetTracks} sources</strong>
          </summary>
          <div className={styles.datasetGrid}>
            {datasetEvidence.map((dataset, index) => (
              <article className={styles.datasetCard} key={dataset.id}>
                <header>
                  <span>{String(index + 1).padStart(2, "0")}</span>
                  <div>
                    <p className={styles.datasetStatus} data-tone={dataset.statusTone}>
                      {dataset.status}
                    </p>
                    <h3>{dataset.shortName}</h3>
                    <small>{dataset.fullName}</small>
                  </div>
                </header>
                <div className={styles.datasetBody}>
                  <div>
                    <span>What job it did</span>
                    <p>{dataset.role}</p>
                  </div>
                  <div>
                    <span>What it taught</span>
                    <p>{dataset.lesson}</p>
                  </div>
                  <div className={styles.datasetResult}>
                    <span>{dataset.resultLabel}</span>
                    <strong>{dataset.resultValue}</strong>
                    <p>{dataset.resultDetail}</p>
                  </div>
                </div>
                <details>
                  <summary>Rights and limits</summary>
                  <p>
                    <strong>Rights:</strong> {dataset.rights}
                  </p>
                  <p>
                    <strong>Does not prove:</strong> {dataset.didNotProve}
                  </p>
                  <a href={dataset.sourceUrl} target="_blank" rel="noreferrer">
                    {dataset.sourceLabel}
                  </a>
                </details>
              </article>
            ))}
          </div>
        </details>
      </section>

      <section className={styles.boschSection} aria-labelledby="bosch-heading">
        <div className={styles.boschCopy}>
          <div className="section-kicker section-kicker-light">
            Reproduced open-data evaluation
          </div>
          <h2 id="bosch-heading">
            Did one unseen machine still look vibrationally similar?
          </h2>
          <p>
            For each test, two machines formed a reference range and the third
            machine was held out—kept away from that reference. A ratio below one
            means the left-out machine’s average feature distance stayed below
            the reference fleet’s 90th-percentile distance.
          </p>
          <div className={styles.boschTruth}>
            <strong>What the result says</strong>
            <span>
              All three machines remained inside the reference vibration
              envelope in this calculation.
            </span>
          </div>
          <div className={styles.boschTruth}>
            <strong>What it does not say</strong>
            <span>
              It is not anomaly-detection accuracy, defect detection, safety
              validation, or field-performance assurance.
            </span>
          </div>
        </div>
        <div className={styles.boschPanel}>
          <div className={styles.boschHeader}>
            <div>
              <span>{evidenceTotals.boschRecordings.toLocaleString()}</span>
              <small>total recordings</small>
            </div>
            <span className={styles.openBadge}>OPEN DATA · CC BY 4.0</span>
          </div>
          <div className={styles.boschBars}>
            {boschHoldouts.map((holdout) => (
              <div key={holdout.machine}>
                <div className={styles.barLabel}>
                  <span>
                    Hold out {holdout.machine}
                    <small>reference: {holdout.referenceMachines}</small>
                  </span>
                  <strong>{holdout.ratio.toFixed(3)}</strong>
                </div>
                <div className={styles.barTrack} aria-hidden="true">
                  <span style={{ width: `${holdout.ratio * 100}%` }} />
                  <i />
                </div>
                <small>{holdout.recordings} unseen-machine recordings</small>
              </div>
            ))}
          </div>
          <p>
            The vertical marker at 1.0 is the reference-envelope boundary used
            by this comparison—not a machine limit.
          </p>
        </div>
      </section>

      <section className={styles.questionsSection}>
        <div className={styles.sectionIntro}>
          <div>
            <div className="section-kicker">Common first questions</div>
            <h2>Short answers before the technical detail.</h2>
          </div>
        </div>
        <div className={styles.questionList}>
          <details>
            <summary>Did all five datasets train one neural network?</summary>
            <p>
              No. The public record shows separate experiments and component
              lessons. There is no publicly auditable checkpoint trained jointly
              on all five, and this site does not imply one.
            </p>
          </details>
          <details>
            <summary>Why show a result that transferred poorly?</summary>
            <p>
              Because a weak held-out result is useful evidence. It shows where
              a relationship stopped generalizing and prevents a good in-sample
              fit from becoming an inflated claim.
            </p>
          </details>
          <details>
            <summary>Why are some datasets under rights review?</summary>
            <p>
              A downloadable research dataset does not always include an
              authoritative license. SAGE keeps scientific findings separate
              from permission to redistribute or use the raw data commercially.
            </p>
          </details>
          <details>
            <summary>Does the simulation prove SAGE improves machining?</summary>
            <p>
              No. It demonstrates inspectable data flow, evidence labels,
              unknown-value handling, and a public demo rule. Physical
              performance requires separately labeled observed evidence.
            </p>
          </details>
        </div>
      </section>

      <section className={styles.glossarySection} id="glossary">
        <div className={styles.sectionIntro}>
          <div>
            <div className="section-kicker">Plain-language glossary</div>
            <h2>Every important term, without assuming prior knowledge.</h2>
          </div>
          <p>
            The technical names remain so an engineer can trace the work, but
            each definition explains what the term means in ordinary language.
          </p>
        </div>
        <dl className={styles.glossaryGrid}>
          {glossaryTerms.map((entry) => (
            <div key={entry.id || entry.term} id={entry.id ? `term-${entry.id}` : undefined}>
              <dt>{entry.term}</dt>
              <dd>{entry.definition}</dd>
            </div>
          ))}
        </dl>
      </section>

      <section className={styles.nextSection}>
        <div>
          <div className="section-kicker section-kicker-light">
            Continue at your own depth
          </div>
          <h2>Start with the picture. Audit the bytes when you are ready.</h2>
          <p>
            The full simulation page exposes every row, the generator, CSV,
            JSON, and SHA-256 fingerprints. The product homepage explains the
            broader platform and roadmap.
          </p>
        </div>
        <div>
          <a className="button button-light" href="/simulation/">
            Open the data explorer
            <ArrowIcon />
          </a>
          <a className={styles.nextLink} href="/#platform">
            Return to the platform overview
          </a>
        </div>
      </section>

      <SiteFooter />
    </main>
  );
}
