import {
  boschHoldouts,
  datasetEvidence,
  evidencePrinciple,
  evidenceTerms,
  evidenceTotals,
} from "../../lib/public-evidence";
import {
  kernelPlainTerms,
  publicKernelBoundary,
  publicKernels,
} from "../../lib/public-kernels";
import {
  publicFusionDescription,
  publicFusionDocumentDownload,
  publicFusionSummary,
  publicSimulationDocumentDownload,
  publicSimulationObjectiveDescription,
  publicSimulationRuntimeDescription,
  publicSimulationSummary,
  publicSurfaceDescription,
  publicSurfaceDocumentDownload,
  publicSurfaceSummary,
} from "../../lib/public-results";
import { siteUrl } from "../../lib/site";
import { ArrowIcon, SiteFooter, SiteHeader } from "../site-chrome";
import EvidenceLab from "./evidence-lab";
import styles from "./evidence.module.css";

export const metadata = {
  title: "Evidence Guide",
  description:
    "Review SAGE Suite's NVIDIA Isaac Sim campaign, multi-sensor digital-twin fusion aggregate, public replay, open-data evaluation, terminology, and measurement boundaries.",
  alternates: {
    canonical: "/evidence/",
  },
  openGraph: {
    title: "Evidence Guide | SAGE Suite",
    description:
      "See aggregate results from 2,542 NVIDIA programs and 497,834 multi-sensor twin episodes—and what they do and do not establish.",
    url: "/evidence/",
    type: "article",
  },
  twitter: {
    title: "Evidence Guide | SAGE Suite",
    description:
      "A plain-language guide to SAGE's twin campaigns, public replay, open-data evaluation, and evidence boundaries.",
  },
};

const evidenceStructuredData = {
  "@context": "https://schema.org",
  "@type": "CollectionPage",
  name: "SAGE Suite public evidence guide",
  description:
    "A plain-language guide to the verified SAGE NVIDIA simulation campaign, public browser replay, Bosch open-data evaluation, historical dataset research, terminology, and rights status.",
  url: `${siteUrl}evidence/`,
  isPartOf: {
    "@type": "WebSite",
    name: "SAGE Suite",
    url: siteUrl,
  },
  about: datasetEvidence.map((dataset) => ({
    "@type": "Dataset",
    name: dataset.fullName,
    url: dataset.sourceUrl,
  })),
};

const evidenceStructuredDataJson = JSON.stringify(evidenceStructuredData).replace(
  /</g,
  "\\u003c",
);

const quickSteps = [
  {
    number: "01",
    title: "Organize the plan",
    body:
      "SAGE represents the manufacturing recipe—setups, tools, operations, and checks—in a form people can review.",
  },
  {
    number: "02",
    title: "Compare candidate plans",
    body:
      "Simulation and shadow learning compare alternatives against a consistent modeled objective while preserving the baseline.",
  },
  {
    number: "03",
    title: "Attach evidence and verify",
    body:
      "A recommendation keeps its sources, labels, unknowns, and independent checks before a qualified human decision.",
  },
];

const evidenceClasses = [
  {
    label: "SIMULATED",
    title: "NVIDIA shadow campaign",
    body:
      "Aggregate evidence from 2,542 shadow programs spanning nine shape/material cells. Useful for showing repeatable within-simulator optimization and evidence capture.",
  },
  {
    label: "SIMULATED",
    title: "Multi-sensor digital-twin fusion",
    body: `Aggregate from ${publicFusionSummary.stressEpisodes.toLocaleString()} latency-stressed fusion episodes across ${publicFusionSummary.workerRuns} GPU workers and a ${publicFusionSummary.sensorCatalogSize}-class catalog. Demonstrates executable twin software for suite ranking under network stress—not field-validated machine accuracy.`,
  },
  {
    label: "SIMULATED · MODELED NOT MEASURED",
    title: "Surface-integrity retrospective",
    body:
      "A finish-pass proxy derived from NVIDIA-run feed, force, acceleration, and temperature trajectories with an explicit historical tool-geometry sensitivity interval.",
  },
  {
    label: "SIMULATED · ILLUSTRATIVE",
    title: "Public teaching replay",
    body:
      "Generated by a public script. Useful for inspecting data flow, labels, unknowns, and a fail-closed demo rule—not for claiming physical performance.",
  },
  {
    label: "OPEN-DATA EVALUATION",
    title: "Bosch vibration boundary",
    body:
      "A reproduced calculation over 1,702 real CNC recordings. It tests cross-machine vibration similarity, not anomaly accuracy.",
  },
  {
    label: "HISTORICAL · RIGHTS REVIEW",
    title: "Earlier research record",
    body:
      "NASA, NUAA, and PHM results remain useful scientific context, but their public reuse rights and current reproduction artifacts are not all established.",
  },
];

const campaignTerms = [
  {
    id: "isaac-sim",
    term: "NVIDIA Isaac Sim",
    definition:
      "A robotics simulation application used here to execute robot articulation. The campaign paired it with mechanistic cutting-load calculations and synthesized high-frequency vibration.",
  },
  {
    id: "scenario-cell",
    term: "Scenario cell",
    definition:
      "One shape/material pairing in the campaign. Three generic pocket shapes crossed with three material models to create nine cells.",
  },
  {
    id: "shadow-mode",
    term: "Shadow mode",
    definition:
      "The software can generate, score, and record recommendations without receiving authority to command physical equipment.",
  },
  {
    id: "synthetic-objective",
    term: "Synthetic objective",
    definition:
      "A modeled score that combines campaign considerations so candidate programs can be compared consistently inside the simulator. Lower is better; it is not a direct shop-floor measurement.",
  },
  {
    id: "model-promotion",
    term: "Model promotion",
    definition:
      "The decision to let a trained model advance into a more trusted role. SAGE withheld promotion when independent held-out and boundary tests did not support authority.",
  },
  {
    id: "surface-integrity-proxy",
    term: "Surface-integrity proxy",
    definition:
      "A modeled indicator that combines kinematic feed-mark context with simulated force, vibration, thermal, runout, and structural context. It is not measured Ra or a surface-quality guarantee.",
  },
];

const glossaryTerms = [
  ...campaignTerms,
  ...kernelPlainTerms,
  ...evidenceTerms,
];

export default function EvidencePage() {
  return (
    <main className={styles.page}>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: evidenceStructuredDataJson }}
      />
      <SiteHeader />

      <section className={styles.hero} id="top">
        <div className={styles.heroCopy}>
          <div className="section-kicker">New to SAGE? Start here.</div>
          <h1>
            See what was tested.
            <span>Understand what it means.</span>
          </h1>
          <p>
            SAGE helps manufacturing teams review CNC process plans, keep
            recommendations tied to evidence, and leave the final decision with
            qualified people. This guide starts with the complete NVIDIA
            simulation campaign, then separates simulated evidence from open
            physical-machine data and historical research.
          </p>
          <div className={styles.heroActions}>
            <a className="button button-primary" href="#simulation-results">
              See the simulation results
              <ArrowIcon />
            </a>
            <a className="button button-secondary" href="#guided-replay">
              Open the guided replay
            </a>
          </div>
          <div className={styles.heroBoundary}>
            <span>2,542 shadow programs</span>
            <span>9 coverage cells</span>
            <span>Simulation clearly labeled</span>
          </div>
        </div>
        <aside className={styles.heroGuide} aria-label="Choose your depth">
          <span>Choose your depth</span>
          <a href="#quick-tour">
            <strong>60 seconds</strong>
            <small>What the platform does</small>
          </a>
          <a href="#simulation-results">
            <strong>2 minutes</strong>
            <small>Full NVIDIA campaign</small>
          </a>
          <a href="#guided-replay">
            <strong>3 minutes</strong>
            <small>Interactive public replay</small>
          </a>
          <a href="#glossary">
            <strong>Reference</strong>
            <small>Every technical term explained</small>
          </a>
        </aside>
      </section>

      <section className={styles.quickTour} id="quick-tour">
        <div className={styles.sectionIntro}>
          <div>
            <div className="section-kicker">SAGE in 60 seconds</div>
            <h2>One workflow for modeling, comparing, and verifying a plan.</h2>
          </div>
          <p>
            A CNC process plan is the manufacturing recipe for making a part.
            SAGE is being built to make that recipe and its supporting evidence
            easier to inspect as one accountable thread.
          </p>
        </div>
        <div className={styles.quickGrid}>
          {quickSteps.map((step) => (
            <article key={step.number}>
              <span>{step.number}</span>
              <h3>{step.title}</h3>
              <p>{step.body}</p>
            </article>
          ))}
        </div>
        <p className={styles.oneLineBoundary}>
          In plain English: SAGE helps a person compare candidate plans, inspect
          the supporting evidence, and make a better-informed decision.
        </p>
      </section>

      <section
        className={styles.resultSection}
        id="simulation-results"
        aria-labelledby="evidence-results-heading"
      >
        <div className={styles.sectionIntro}>
          <div>
            <div className="section-kicker">Verified NVIDIA simulation campaign</div>
            <h2 id="evidence-results-heading">
              All 2,542 shadow programs scored below their simulated baselines.
            </h2>
          </div>
          <p>
            The median reduction was{" "}
            {publicSimulationSummary.medianReductionPercent.toFixed(1)}%. Each
            comparison used the same bounded synthetic objective for a program
            and its own baseline inside the simulator.
          </p>
        </div>
        <div className={styles.resultGrid}>
          <article>
            <span>SIMULATED · CAMPAIGN MEDIAN</span>
            <strong>
              {publicSimulationSummary.medianReductionPercent.toFixed(1)}%
            </strong>
            <h3>lower synthetic objective</h3>
            <p>
              Typical 80% ranged from{" "}
              {publicSimulationSummary.p10ReductionPercent.toFixed(1)}% to{" "}
              {publicSimulationSummary.p90ReductionPercent.toFixed(1)}%.
            </p>
          </article>
          <article>
            <span>SIMULATED · PROGRAMS</span>
            <strong>{publicSimulationSummary.programCount.toLocaleString()}</strong>
            <h3>program comparisons</h3>
            <p>All used a same-simulator, same-objective baseline.</p>
          </article>
          <article>
            <span>INTEGRITY · VERIFIED</span>
            <strong>{publicSimulationSummary.archiveCount}</strong>
            <h3>reconciled shard archives</h3>
            <p>Program, provenance, policy, and learning records matched.</p>
          </article>
          <article>
            <span>SIMULATED · MODELED FINISH CONTEXT</span>
            <strong>{publicSurfaceSummary.midpointMedianUm.toFixed(2)}</strong>
            <h3>µm median proxy midpoint</h3>
            <p>
              Median interval: {publicSurfaceSummary.lowerMedianUm.toFixed(2)}–
              {publicSurfaceSummary.upperMedianUm.toFixed(2)} µm. Not measured
              Ra; modeled, not measured.
            </p>
          </article>
        </div>
        <div className={styles.resultMeaning}>
          <div>
            <strong>What “simulation objective” means</strong>
            <p>{publicSimulationObjectiveDescription}</p>
          </div>
          <div>
            <strong>What ran in NVIDIA Isaac Sim</strong>
            <p>{publicSimulationRuntimeDescription}</p>
          </div>
          <div>
            <strong>What the surface-integrity interval means</strong>
            <p>{publicSurfaceDescription}</p>
          </div>
          <div>
            <strong>What the multi-sensor twin means</strong>
            <p>{publicFusionDescription}</p>
          </div>
        </div>
        <div className={styles.modelDecision}>
          <div>
            <span>Fail-closed model decision</span>
            <strong>Campaign integrity passed. Model promotion did not.</strong>
          </div>
          <p>
            Independent held-out and generated-boundary checks did not support
            authority for the saved surrogate, so SAGE withheld promotion. That
            refusal is part of the evidence, not a hidden exception. The fusion
            twin similarly ranks suites under latency without granting machine
            authority.
          </p>
          <div className={styles.modelDownloads}>
            <a href={publicSimulationDocumentDownload} download>
              Campaign aggregate JSON
            </a>
            <a href={publicSurfaceDocumentDownload} download>
              Surface aggregate JSON
            </a>
            <a href={publicFusionDocumentDownload} download>
              Fusion twin aggregate JSON
            </a>
          </div>
        </div>
      </section>

      <section className={styles.kernelSection} id="kernels">
        <div className={styles.sectionIntro}>
          <div>
            <div className="section-kicker">Five assurance kernels</div>
            <h2>Five focused checks. Five reasons to refuse.</h2>
          </div>
          <p>
            “Kernel” here means a small, focused software check—not an operating
            system, machine controller, or certified safety device. Each kernel
            asks a different question before an advisory result can continue.
          </p>
        </div>
        <div className={styles.kernelGrid}>
          {publicKernels.map((kernel) => (
            <article key={kernel.number}>
              <header>
                <span>{kernel.number}</span>
                <h3>{kernel.shortName}</h3>
              </header>
              <p className={styles.kernelQuestion}>{kernel.question}</p>
              <div>
                <span>If the answer is no</span>
                <p>{kernel.action}</p>
              </div>
              <small>{kernel.value}</small>
            </article>
          ))}
        </div>
        <div className={styles.kernelBoundary}>
          <strong>Public description boundary</strong>
          <p>{publicKernelBoundary}</p>
        </div>
      </section>

      <section className={styles.classSection} aria-labelledby="classes-heading">
        <div className={styles.sectionIntro}>
          <div>
            <div className="section-kicker">Three evidence classes</div>
            <h2 id="classes-heading">Different evidence answers different questions.</h2>
          </div>
          <p>
            Keeping these classes separate prevents a polished simulation from
            being mistaken for real-machine validation.
          </p>
        </div>
        <div className={styles.classGrid}>
          {evidenceClasses.map((item) => (
            <article key={item.label}>
              <span>{item.label}</span>
              <h3>{item.title}</h3>
              <p>{item.body}</p>
            </article>
          ))}
        </div>
      </section>

      <section className={styles.labSection} id="guided-replay">
        <div className={styles.sectionIntro}>
          <div>
            <div className="section-kicker">Public simulation · 120 rows</div>
            <h2>A browser twin you can inspect, not just watch.</h2>
          </div>
          <p>
            This generic scene is synchronized to the same downloadable
            simulation data shown in the chart and readouts. It is a teaching
            interface, not a physical digital twin.
          </p>
        </div>
        <EvidenceLab />
        <div className={styles.labActions}>
          <a className="button button-primary" href="/simulation/">
            Inspect all 120 rows
            <ArrowIcon />
          </a>
          <a
            className="button button-secondary"
            href="/data/sage-public-simulation-v1.csv"
            download
          >
            Download the CSV
          </a>
        </div>
      </section>

      <section className={styles.lineageSection} id="dataset-ledger">
        <div className={styles.sectionIntro}>
          <div>
            <div className="section-kicker">Optional technical depth</div>
            <h2>The supporting research ledger.</h2>
          </div>
          <p>
            Dataset work is one supporting part of the suite, not its organizing
            idea. Open this ledger to trace which sources informed separate
            experiments and where the evidence or reuse rights remain limited.
          </p>
        </div>

        <details className={styles.datasetDisclosure}>
          <summary>
            <span>
              Open the five-source research ledger
              <small>{evidencePrinciple}</small>
            </span>
            <strong>{evidenceTotals.datasetTracks} sources</strong>
          </summary>
          <div className={styles.datasetGrid}>
            {datasetEvidence.map((dataset, index) => (
              <article className={styles.datasetCard} key={dataset.id}>
                <header>
                  <span>{String(index + 1).padStart(2, "0")}</span>
                  <div>
                    <p className={styles.datasetStatus} data-tone={dataset.statusTone}>
                      {dataset.status}
                    </p>
                    <h3>{dataset.shortName}</h3>
                    <small>{dataset.fullName}</small>
                  </div>
                </header>
                <div className={styles.datasetBody}>
                  <div>
                    <span>What job it did</span>
                    <p>{dataset.role}</p>
                  </div>
                  <div>
                    <span>What it taught</span>
                    <p>{dataset.lesson}</p>
                  </div>
                  <div className={styles.datasetResult}>
                    <span>{dataset.resultLabel}</span>
                    <strong>{dataset.resultValue}</strong>
                    <p>{dataset.resultDetail}</p>
                  </div>
                </div>
                <details>
                  <summary>Rights and limits</summary>
                  <p>
                    <strong>Rights:</strong> {dataset.rights}
                  </p>
                  <p>
                    <strong>Does not prove:</strong> {dataset.didNotProve}
                  </p>
                  <a href={dataset.sourceUrl} target="_blank" rel="noreferrer">
                    {dataset.sourceLabel}
                  </a>
                </details>
              </article>
            ))}
          </div>
        </details>
      </section>

      <section className={styles.boschSection} aria-labelledby="bosch-heading">
        <div className={styles.boschCopy}>
          <div className="section-kicker section-kicker-light">
            Reproduced open-data evaluation
          </div>
          <h2 id="bosch-heading">
            Did one unseen machine still look vibrationally similar?
          </h2>
          <p>
            For each test, two machines formed a reference range and the third
            machine was held out—kept away from that reference. A ratio below one
            means the left-out machine’s average feature distance stayed below
            the reference fleet’s 90th-percentile distance.
          </p>
          <div className={styles.boschTruth}>
            <strong>What the result says</strong>
            <span>
              All three machines remained inside the reference vibration
              envelope in this calculation.
            </span>
          </div>
          <div className={styles.boschTruth}>
            <strong>What it does not say</strong>
            <span>
              It is not anomaly-detection accuracy, defect detection, safety
              validation, or field-performance assurance.
            </span>
          </div>
        </div>
        <div className={styles.boschPanel}>
          <div className={styles.boschHeader}>
            <div>
              <span>{evidenceTotals.boschRecordings.toLocaleString()}</span>
              <small>total recordings</small>
            </div>
            <span className={styles.openBadge}>OPEN DATA · CC BY 4.0</span>
          </div>
          <div className={styles.boschBars}>
            {boschHoldouts.map((holdout) => (
              <div key={holdout.machine}>
                <div className={styles.barLabel}>
                  <span>
                    Hold out {holdout.machine}
                    <small>reference: {holdout.referenceMachines}</small>
                  </span>
                  <strong>{holdout.ratio.toFixed(3)}</strong>
                </div>
                <div className={styles.barTrack} aria-hidden="true">
                  <span style={{ width: `${holdout.ratio * 100}%` }} />
                  <i />
                </div>
                <small>{holdout.recordings} unseen-machine recordings</small>
              </div>
            ))}
          </div>
          <p>
            The vertical marker at 1.0 is the reference-envelope boundary used
            by this comparison—not a machine limit.
          </p>
        </div>
      </section>

      <section className={styles.questionsSection}>
        <div className={styles.sectionIntro}>
          <div>
            <div className="section-kicker">Common first questions</div>
            <h2>Short answers before the technical detail.</h2>
          </div>
        </div>
        <div className={styles.questionList}>
          <details>
            <summary>Did all five datasets train one neural network?</summary>
            <p>
              No. The public record shows separate experiments and component
              lessons. There is no publicly auditable checkpoint trained jointly
              on all five, and this site does not imply one.
            </p>
          </details>
          <details>
            <summary>Why show a result that transferred poorly?</summary>
            <p>
              Because a weak held-out result is useful evidence. It shows where
              a relationship stopped generalizing and prevents a good in-sample
              fit from becoming an inflated claim.
            </p>
          </details>
          <details>
            <summary>Why are some datasets under rights review?</summary>
            <p>
              A downloadable research dataset does not always include an
              authoritative license. SAGE keeps scientific findings separate
              from permission to redistribute or use the raw data commercially.
            </p>
          </details>
          <details>
            <summary>What improvement does the NVIDIA campaign establish?</summary>
            <p>
              It establishes repeatable improvement against each program&apos;s
              own baseline inside the campaign&apos;s synthetic objective:
              2,542 of 2,542 comparisons were lower, with a 46.7% median
              reduction. It does not convert that modeled result into a claim of
              measured cycle time, part quality, physical cutting, or safety
              performance.
            </p>
          </details>
        </div>
      </section>

      <section className={styles.glossarySection} id="glossary">
        <div className={styles.sectionIntro}>
          <div>
            <div className="section-kicker">Plain-language glossary</div>
            <h2>Every important term, without assuming prior knowledge.</h2>
          </div>
          <p>
            The technical names remain so an engineer can trace the work, but
            each definition explains what the term means in ordinary language.
          </p>
        </div>
        <dl className={styles.glossaryGrid}>
          {glossaryTerms.map((entry) => (
            <div key={entry.id || entry.term} id={entry.id ? `term-${entry.id}` : undefined}>
              <dt>{entry.term}</dt>
              <dd>{entry.definition}</dd>
            </div>
          ))}
        </dl>
      </section>

      <section className={styles.nextSection}>
        <div>
          <div className="section-kicker section-kicker-light">
            Continue at your own depth
          </div>
          <h2>Start with the picture. Audit the bytes when you are ready.</h2>
          <p>
            The full simulation page exposes every row, the generator, CSV,
            JSON, and SHA-256 fingerprints. The product homepage explains the
            broader platform and roadmap.
          </p>
        </div>
        <div>
          <a className="button button-light" href="/simulation/">
            Open the data explorer
            <ArrowIcon />
          </a>
          <a className={styles.nextLink} href="/#platform">
            Return to the platform overview
          </a>
        </div>
      </section>

      <SiteFooter />
    </main>
  );
}
